name: flutter_paginate
description: >
  A simple widget for a pagination.
  Easy to use and fleely customizable.
version: 1.0.0
homepage: https://github.com/rbdog/flutter_paginate
repository: https://github.com/rbdog/flutter_paginate

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

